# Example Site settings

 # google_analytics: UA-NNNNNNNN-N

header_pages: 
"Hey, I'm Mihir Walia!"
  - index.md #edu,exp
  - skills.md #skills
  - projects.md #projects
  - certs.md #certifications
  - contact.md #contact
  - blog.md #blog
  

footer: "Are you a One or a Zero?"

style: hacker #light  dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
