# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages: 
  - index.md #edu,exp
  - skills.md #skills
  - projects.md #projects
  - certs.md #certifications
  - contact.md #contact
  #- blog.md #blog
  

footer: 'Hi, I'm Mihir Walia!'

style: hacker #light  dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
