# Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md #edu,exp
  - about.md #skills
  - projects.md #projects
  - contact.md #contact
  - blog.md #blog
  

footer: 'Contact me: <a href="https://www.linkedin.com/in/mihir-walia-972642173/">LinkedIn</a>'

style: hacker #light  dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
